import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Banner from '../components/Banner/Banner.jsx';
export default function Home() {
	const handleOnBannerButtonClick = () => {
		console.log('hi clicked');
	};
	return (
		<div className={styles.container}>
			<Head>
				<title>Our Cofee App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<h1>Coffee Shop</h1>
				<Banner buttonText='View stores nearby' handleOnClick={handleOnBannerButtonClick} />
				<div className={styles.heroImage}>
					<Image src='/static/hero-image.png' width={700} height={400} alt='hero-image' />
				</div>
			</main>

			<footer className={styles.footer}></footer>
		</div>
	);
}
